apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc
  namespace: dev # Specify the namespace
spec:
  accessModes:
    - ReadWriteOnce  # Access mode (must match the PV's access mode)
  resources:
    requests:
      storage: 2Gi  # Size requested for the PVC
  storageClassName: standard  # Should match the PV's storage class (optional)
